/**
 * ExecuteGetMarginPerConnectionReport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetMarginPerConnectionReport Use Case
 *
 * DDD: Application use case for get MarginReport.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetMarginPerConnectionReportInput, GetMarginPerConnectionReportOutput } from "../dto/margin-report.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { MarginReportClient } from "../ports";

export class ExecuteGetMarginPerConnectionReport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly marginReport: MarginReportClient
  ) {}

  async execute(input: GetMarginPerConnectionReportInput): Promise<GetMarginPerConnectionReportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stlId();

    // TODO: Implement get logic
    throw new Error("Use case not yet implemented");
  }
}
