/**
 * ExecuteIssueFlatRateInvoice - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteIssueFlatRateInvoice Use Case
 *
 * DDD: Application use case for get Invoice.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { IssueFlatRateInvoiceInput, IssueFlatRateInvoiceOutput } from "../dto/invoice.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { InvoiceRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteIssueFlatRateInvoice {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly invoice: InvoiceRepository
  ) {}

  async execute(input: IssueFlatRateInvoiceInput): Promise<IssueFlatRateInvoiceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stlId();

    // All field names extracted from OpenAPI spec: guaranteeId, period
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).guaranteeId) {
      throw new ValidationError("guaranteeId is required");
    }
    const guaranteeId = (input as any).guaranteeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.invoice.issueFlatRateInvoice({ guaranteeId: guaranteeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${guaranteeId}`);
    }

    return entity as IssueFlatRateInvoiceOutput;
  }
}
