/**
 * ExecuteListFlatRateInvoices - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListFlatRateInvoices Use Case
 *
 * DDD: Application use case for list Invoice.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListFlatRateInvoicesInput, ListFlatRateInvoicesOutput } from "../dto/invoice.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { InvoiceRepository } from "../ports";

export class ExecuteListFlatRateInvoices {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly invoice: InvoiceRepository
  ) {}

  async execute(input: ListFlatRateInvoicesInput): Promise<ListFlatRateInvoicesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stlId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.invoice.listFlatRateInvoices({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListFlatRateInvoicesOutput;
  }
}
