/**
 * ExecuteIngestConditionMeasurement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteIngestConditionMeasurement Use Case
 *
 * DDD: Application use case for get ConditionMeasurement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { IngestConditionMeasurementInput, IngestConditionMeasurementOutput } from "../dto/condition-measurement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { ConditionMeasurementRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteIngestConditionMeasurement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly conditionMeasurement: ConditionMeasurementRepository
  ) {}

  async execute(input: IngestConditionMeasurementInput): Promise<IngestConditionMeasurementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stlId();

    // All field names extracted from OpenAPI spec: connectionId, hotWaterAvailable, hotWaterTemperatureC, indoorTemperatureC, measuredAt, measurementPoint, withinGuarantee
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).connectionId) {
      throw new ValidationError("connectionId is required");
    }
    const connectionId = (input as any).connectionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.conditionMeasurement.ingestConditionMeasurement({ connectionId: connectionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${connectionId}`);
    }

    return entity as IngestConditionMeasurementOutput;
  }
}
