/**
 * Advisory DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Advisory Domain Module - Composition root
 *
 * DDD: Composition root for advisory domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BenchmarkRepositoryAdapter,
  ConditionReportRepositoryAdapter,
  RemediationProposalRepositoryAdapter,
} from "@warmpact/adapters/advisory";
import { getIdGeneratorService } from "@warmpact/adapters";
import type { AdapterDynamoDBClient } from "@warmpact/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetBenchmarkCohort,
  ExecuteGetPlainLanguageConditionReport,
  ExecuteIssueRemediationProposal,
  ExecuteListRemediationProposals,
} from "@warmpact/services/advisory/usecases";
// Ports (interfaces)
import type {
  BenchmarkRepository,
  ConditionReportRepository,
  RemediationProposalRepository,
} from "@warmpact/services/advisory/ports";

export interface AdvisoryDomainModule {
  repos: {
    benchmarks: BenchmarkRepository;
    conditionReports: ConditionReportRepository;
    remediationProposals: RemediationProposalRepository;
  };
  useCases: {
    benchmarks: {
      get: ExecuteGetBenchmarkCohort;
    };
    conditionReports: {
      get: ExecuteGetPlainLanguageConditionReport;
    };
    remediationProposals: {
      get: ExecuteIssueRemediationProposal;
      list: ExecuteListRemediationProposals;
    };
  };
}

export function buildAdvisoryDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AdvisoryDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      benchmarks?: BenchmarkRepository;
      conditionReports?: ConditionReportRepository;
      remediationProposals?: RemediationProposalRepository;
    } = {};

    obj.benchmarks = new BenchmarkRepositoryAdapter(dynamoClient);
    obj.conditionReports = new ConditionReportRepositoryAdapter(dynamoClient);
    obj.remediationProposals = new RemediationProposalRepositoryAdapter(dynamoClient);
    return {
      benchmarks: obj.benchmarks!,
      conditionReports: obj.conditionReports!,
      remediationProposals: obj.remediationProposals!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    benchmarks: {
      get: new ExecuteGetBenchmarkCohort(executionContext, idGenerator, repos.benchmarks),
    },
    conditionReports: {
      get: new ExecuteGetPlainLanguageConditionReport(executionContext, idGenerator, repos.conditionReports),
    },
    remediationProposals: {
      get: new ExecuteIssueRemediationProposal(executionContext, idGenerator, repos.remediationProposals),
      list: new ExecuteListRemediationProposals(executionContext, idGenerator, repos.remediationProposals),
    },
  };
  return { repos, useCases: useCases as AdvisoryDomainModule["useCases"] };
}
