/**
 * Connection DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Connection DTOs
 *
 * DDD: Application DTOs for Connection use cases.
 */

import type { GetBuildingConnectionParams, ListBuildingConnectionsParams, RegisterBuildingConnectionRequestInput } from "@warmpact/core/customers/types";

export type ListBuildingConnectionsInput = ListBuildingConnectionsParams;

export type RegisterBuildingConnectionInput = RegisterBuildingConnectionRequestInput;

export type GetBuildingConnectionInput = GetBuildingConnectionParams;

export type ListBuildingConnectionsOutput = {};

export type RegisterBuildingConnectionOutput = {};

export type GetBuildingConnectionOutput = {};
