/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: underwriting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./thermal-model-repository.ddb.js";
export * from "./underwriting-repository.ddb.js";
export * from "./thermal-model-repository.adapter.js";
export * from "./underwriting-client.adapter.js";
export * from "./underwriting-repository.adapter.js";
