/**
 * ThermalModelRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: underwriting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ThermalModelRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ThermalModelRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ThermalModelRepository,
} from "@warmpact/services/underwriting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ThermalModelRepositoryDdb } from "./thermal-model-repository.ddb.js";

/**
 * ThermalModelRepositoryAdapter
 *
 * Implements ThermalModelRepository port for infrastructure layer.
 */
export class ThermalModelRepositoryAdapter implements ThermalModelRepository {
  private readonly ddb: ThermalModelRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ThermalModelRepositoryDdb(this.dynamoClient);
  }

  async getBuildingThermalModel(input: Parameters<ThermalModelRepository['getBuildingThermalModel']>[0]): Promise<Awaited<ReturnType<ThermalModelRepository['getBuildingThermalModel']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getBuildingThermalModel(input);
  }
}
