/**
 * ExecuteBuildFlatRatePrice - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteBuildFlatRatePrice Use Case
 *
 * DDD: Application use case for get FlatRate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { BuildFlatRatePriceInput, BuildFlatRatePriceOutput } from "../dto/flat-rate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { FlatRateRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteBuildFlatRatePrice {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly flatRate: FlatRateRepository
  ) {}

  async execute(input: BuildFlatRatePriceInput): Promise<BuildFlatRatePriceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prcId();

    // All field names extracted from OpenAPI spec: carbonPricePerTonne, conditionProductId, connectionId, degreeDayNormalYear
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).conditionProductId) {
      throw new ValidationError("conditionProductId is required");
    }
    const conditionproductId = (input as any).conditionProductId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.flatRate.buildFlatRatePrice({ conditionProductId: conditionproductId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${conditionproductId}`);
    }

    return entity as BuildFlatRatePriceOutput;
  }
}
