/**
 * ListGuarantee DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListConditionGuaranteesParams } from "@warmpact/core/guarantees";

export function createListGuaranteeRequest(overrides: Partial<ListConditionGuaranteesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
