/**
 * RevisionTrigger Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/pricing.openapi.types.js";
import { schemas } from "../schemas/pricing.schemas.js";

/**
 * Entity: RevisionTriggerEntity
 * Description: Represents the RevisionTrigger domain model.
 * Source: schemas.RevisionTrigger
 * Type: Domain Entity (API)
 */
export const RevisionTriggerEntitySchema = schemas.RevisionTrigger;
export type RevisionTriggerEntity = components["schemas"]["RevisionTrigger"];
