/**
 * Handlers for Guarantee
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GuaranteesDomainModule } from "../dependencies/guarantees-ddd.dependencies.js";
import type { ListConditionGuaranteesInput, OfferConditionGuaranteeInput } from "@warmpact/services/guarantees";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/guarantees
 * Operation: listConditionGuarantees
 */
export async function listConditionGuarantees(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: GuaranteesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListConditionGuaranteesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.guarantees.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/guarantees
 * Operation: offerConditionGuarantee
 */
export async function offerConditionGuarantee(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GuaranteesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OfferConditionGuaranteeInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.guarantees.get.execute(input);
  return reply.code(201).send(result);
}


