/**
 * Handlers for OverrideAttempt
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GuaranteesDomainModule } from "../dependencies/guarantees-ddd.dependencies.js";
import type { AttemptSafetyFloorOverrideInput } from "@warmpact/services/guarantees";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/safety-floors/override-attempts
 * Operation: attemptSafetyFloorOverride
 */
export async function attemptSafetyFloorOverride(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GuaranteesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AttemptSafetyFloorOverrideInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.overrideAttempts.get.execute(input);
  return reply.code(200).send(result);
}


