/**
 * ExecuteListHeatCustomers - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListHeatCustomers Use Case
 *
 * DDD: Application use case for list Customer.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListHeatCustomersInput, ListHeatCustomersOutput } from "../dto/customer.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { CustomerRepository } from "../ports";

export class ExecuteListHeatCustomers {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly customer: CustomerRepository
  ) {}

  async execute(input: ListHeatCustomersInput): Promise<ListHeatCustomersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cstId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.customer.listHeatCustomers({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListHeatCustomersOutput;
  }
}
