/**
 * ExecuteListSwitchRiskSignals - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListSwitchRiskSignals Use Case
 *
 * DDD: Application use case for list SwitchRiskSignal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListSwitchRiskSignalsInput, ListSwitchRiskSignalsOutput } from "../dto/switch-risk-signal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { SwitchRiskSignalRepository } from "../ports";

export class ExecuteListSwitchRiskSignals {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly switchRiskSignal: SwitchRiskSignalRepository
  ) {}

  async execute(input: ListSwitchRiskSignalsInput): Promise<ListSwitchRiskSignalsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cstId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.switchRiskSignal.listSwitchRiskSignals({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListSwitchRiskSignalsOutput;
  }
}
