/**
 * ConditionMeasurement Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/settlement.openapi.types.js";
import { schemas } from "../schemas/settlement.schemas.js";

/**
 * Entity: ConditionMeasurementEntity
 * Description: Represents the ConditionMeasurement domain model.
 * Source: schemas.ConditionMeasurement
 * Type: Domain Entity (API)
 */
export const ConditionMeasurementEntitySchema = schemas.ConditionMeasurement;
export type ConditionMeasurementEntity = components["schemas"]["ConditionMeasurement"];
