/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Advisory Domain Use Cases
 * 
 * List of all use case names for the advisory domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ADVISORY_USE_CASES = [
  "executeGetBenchmarkCohort",
  "executeGetPlainLanguageConditionReport",
  "executeIssueRemediationProposal",
  "executeListRemediationProposals"
] as const;
