/**
 * ReturnTemperatureRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReturnTemperatureRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReturnTemperatureRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReturnTemperatureRepository,
} from "@warmpact/services/network";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReturnTemperatureRepositoryDdb } from "./return-temperature-repository.ddb.js";

/**
 * ReturnTemperatureRepositoryAdapter
 *
 * Implements ReturnTemperatureRepository port for infrastructure layer.
 */
export class ReturnTemperatureRepositoryAdapter implements ReturnTemperatureRepository {
  private readonly ddb: ReturnTemperatureRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReturnTemperatureRepositoryDdb(this.dynamoClient);
  }

  async listReturnTemperatureRecords(input: Parameters<ReturnTemperatureRepository['listReturnTemperatureRecords']>[0]): Promise<Awaited<ReturnType<ReturnTemperatureRepository['listReturnTemperatureRecords']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listReturnTemperatureRecords(input);
  }

  async ingestReturnTemperatureRecord(input: Parameters<ReturnTemperatureRepository['ingestReturnTemperatureRecord']>[0]): Promise<Awaited<ReturnType<ReturnTemperatureRepository['ingestReturnTemperatureRecord']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.ingestReturnTemperatureRecord(input);
  }
}
