/**
 * BindingConnectionClient Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BindingConnectionClient Port
 *
 * DDD: Application port for bindingconnectionclient operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListBindingConnectionConstraintsInput, ListBindingConnectionConstraintsOutput } from "../dto/binding-connection.dto";
export interface BindingConnectionClient {
  listBindingConnectionConstraints(input: ListBindingConnectionConstraintsInput): Promise<ListBindingConnectionConstraintsOutput>;
}

export type { ListBindingConnectionConstraintsInput, ListBindingConnectionConstraintsOutput } from "../dto/binding-connection.dto";
