/**
 * ReturnTemperatureRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReturnTemperatureRepository Port
 *
 * DDD: Application port for returntemperaturerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { IngestReturnTemperatureRecordInput, IngestReturnTemperatureRecordOutput, ListReturnTemperatureRecordsInput, ListReturnTemperatureRecordsOutput } from "../dto/return-temperature.dto";
export interface ReturnTemperatureRepository {
  listReturnTemperatureRecords(input: ListReturnTemperatureRecordsInput): Promise<ListReturnTemperatureRecordsOutput>;
  ingestReturnTemperatureRecord(input: IngestReturnTemperatureRecordInput): Promise<IngestReturnTemperatureRecordOutput>;
}

export type { IngestReturnTemperatureRecordInput, IngestReturnTemperatureRecordOutput, ListReturnTemperatureRecordsInput, ListReturnTemperatureRecordsOutput } from "../dto/return-temperature.dto";
