/**
 * SetpointRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SetpointRepository Port
 *
 * DDD: Application port for setpointrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { IssueSupplyTemperatureSetpointInput, IssueSupplyTemperatureSetpointOutput, ListSupplyTemperatureSetpointsInput, ListSupplyTemperatureSetpointsOutput } from "../dto/setpoint.dto";
export interface SetpointRepository {
  listSupplyTemperatureSetpoints(input: ListSupplyTemperatureSetpointsInput): Promise<ListSupplyTemperatureSetpointsOutput>;
  issueSupplyTemperatureSetpoint(input: IssueSupplyTemperatureSetpointInput): Promise<IssueSupplyTemperatureSetpointOutput>;
}

export type { IssueSupplyTemperatureSetpointInput, IssueSupplyTemperatureSetpointOutput, ListSupplyTemperatureSetpointsInput, ListSupplyTemperatureSetpointsOutput } from "../dto/setpoint.dto";
