/**
 * ConditionProductRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConditionProductRepository Port
 *
 * DDD: Application port for conditionproductrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateConditionProductInput, CreateConditionProductOutput, ListConditionProductsInput, ListConditionProductsOutput } from "../dto/condition-product.dto";
export interface ConditionProductRepository {
  listConditionProducts(input: ListConditionProductsInput): Promise<ListConditionProductsOutput>;
  createConditionProduct(input: CreateConditionProductInput): Promise<CreateConditionProductOutput>;
}

export type { CreateConditionProductInput, CreateConditionProductOutput, ListConditionProductsInput, ListConditionProductsOutput } from "../dto/condition-product.dto";
