/**
 * ExitPackageRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExitPackageRepository Port
 *
 * DDD: Application port for exitpackagerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ReleaseExitPackageInput, ReleaseExitPackageOutput } from "../dto/exit-package.dto";
export interface ExitPackageRepository {
  releaseExitPackage(input: ReleaseExitPackageInput): Promise<ReleaseExitPackageOutput>;
}

export type { ReleaseExitPackageInput, ReleaseExitPackageOutput } from "../dto/exit-package.dto";
