/**
 * Customers Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const registerBuildingConnection_Body = z
  .object({
    customerId: z.string(),
    address: z.string(),
    heatedFloorAreaM2: z.number().optional(),
    buildYear: z.number().int().optional(),
    networkZone: z.string(),
  })
  .passthrough();

export const schemas: any = {
  registerBuildingConnection_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/connections',
    alias: 'listBuildingConnections',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'customerId',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'contractStatus',
        type: 'Query',
        schema: z
          .enum([
            'metered_tariff',
            'under_underwriting',
            'condition_contract',
            'exited',
          ])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string(),
                  customerId: z.string(),
                  address: z.string(),
                  heatedFloorAreaM2: z.number().optional(),
                  buildYear: z.number().int().optional(),
                  lastRenovationYear: z.number().int().optional(),
                  networkZone: z.string().optional(),
                  contractStatus: z.enum([
                    'metered_tariff',
                    'under_underwriting',
                    'condition_contract',
                    'exited',
                  ]),
                  substation: z
                    .object({
                      id: z.string(),
                      connectionId: z.string(),
                      heatExchangerCapacityKw: z.number(),
                      commissioningYear: z.number().int().optional(),
                      remotelyReadable: z.boolean().optional(),
                      controlValveType: z.string().optional(),
                      healthScore: z.number().int().gte(1).lte(5).optional(),
                    })
                    .passthrough()
                    .optional(),
                  annualHeatDemandMwh: z.number().optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/connections',
    alias: 'registerBuildingConnection',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: registerBuildingConnection_Body,
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string(),
            customerId: z.string(),
            address: z.string(),
            heatedFloorAreaM2: z.number().optional(),
            buildYear: z.number().int().optional(),
            lastRenovationYear: z.number().int().optional(),
            networkZone: z.string().optional(),
            contractStatus: z.enum([
              'metered_tariff',
              'under_underwriting',
              'condition_contract',
              'exited',
            ]),
            substation: z
              .object({
                id: z.string(),
                connectionId: z.string(),
                heatExchangerCapacityKw: z.number(),
                commissioningYear: z.number().int().optional(),
                remotelyReadable: z.boolean().optional(),
                controlValveType: z.string().optional(),
                healthScore: z.number().int().gte(1).lte(5).optional(),
              })
              .passthrough()
              .optional(),
            annualHeatDemandMwh: z.number().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough(),
      })
      .passthrough(),
    errors: [
      {
        status: 422,
        description: `Semantically invalid request (e.g. PACK_EMPTY)`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/connections/:connectionId',
    alias: 'getBuildingConnection',
    requestFormat: 'json',
    parameters: [
      {
        name: 'connectionId',
        type: 'Path',
        schema: z.string(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string(),
            customerId: z.string(),
            address: z.string(),
            heatedFloorAreaM2: z.number().optional(),
            buildYear: z.number().int().optional(),
            lastRenovationYear: z.number().int().optional(),
            networkZone: z.string().optional(),
            contractStatus: z.enum([
              'metered_tariff',
              'under_underwriting',
              'condition_contract',
              'exited',
            ]),
            substation: z
              .object({
                id: z.string(),
                connectionId: z.string(),
                heatExchangerCapacityKw: z.number(),
                commissioningYear: z.number().int().optional(),
                remotelyReadable: z.boolean().optional(),
                controlValveType: z.string().optional(),
                healthScore: z.number().int().gte(1).lte(5).optional(),
              })
              .passthrough()
              .optional(),
            annualHeatDemandMwh: z.number().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough(),
      })
      .passthrough(),
    errors: [
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/customers',
    alias: 'listHeatCustomers',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'segment',
        type: 'Query',
        schema: z
          .enum([
            'housing_company',
            'single_occupant_house',
            'public_organisation',
            'business_industry_entrepreneur',
          ])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string(),
                  name: z.string(),
                  segment: z.enum([
                    'housing_company',
                    'single_occupant_house',
                    'public_organisation',
                    'business_industry_entrepreneur',
                  ]),
                  buildingManagerOrganisation: z.string().optional(),
                  connectionIds: z.array(z.string()).optional(),
                  alternativeHeatingRisk: z
                    .enum(['low', 'medium', 'high'])
                    .optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/switch-risk-signals',
    alias: 'listSwitchRiskSignals',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'riskLevel',
        type: 'Query',
        schema: z.enum(['low', 'medium', 'high']).optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string(),
                  customerId: z.string(),
                  connectionId: z.string().optional(),
                  riskLevel: z.enum(['low', 'medium', 'high']),
                  signals: z.array(
                    z.enum([
                      'heat_pump_quote',
                      'competitor_offer',
                      'renovation_project',
                      'complaint_volume',
                      'contract_end_approaching',
                    ])
                  ),
                  detectedAt: z.string().datetime({ offset: true }).optional(),
                  notes: z.string().optional(),
                })
                .passthrough()
            ),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
