/**
 * ListBreach DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListGuaranteeBreachesParams } from "@warmpact/core/settlement";

export function createListBreachRequest(overrides: Partial<ListGuaranteeBreachesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
