/**
 * ConditionReportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConditionReportRepository Port
 *
 * DDD: Application port for conditionreportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetPlainLanguageConditionReportInput, GetPlainLanguageConditionReportOutput } from "../dto/condition-report.dto";
export interface ConditionReportRepository {
  getPlainLanguageConditionReport(input: GetPlainLanguageConditionReportInput): Promise<GetPlainLanguageConditionReportOutput>;
}

export type { GetPlainLanguageConditionReportInput, GetPlainLanguageConditionReportOutput } from "../dto/condition-report.dto";
