/**
 * RemediationProposalRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RemediationProposalRepository Port
 *
 * DDD: Application port for remediationproposalrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { IssueRemediationProposalInput, IssueRemediationProposalOutput, ListRemediationProposalsInput, ListRemediationProposalsOutput } from "../dto/remediation-proposal.dto";
export interface RemediationProposalRepository {
  listRemediationProposals(input: ListRemediationProposalsInput): Promise<ListRemediationProposalsOutput>;
  issueRemediationProposal(input: IssueRemediationProposalInput): Promise<IssueRemediationProposalOutput>;
}

export type { IssueRemediationProposalInput, IssueRemediationProposalOutput, ListRemediationProposalsInput, ListRemediationProposalsOutput } from "../dto/remediation-proposal.dto";
