/**
 * ThermalModelRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: underwriting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ThermalModelRepository Port
 *
 * DDD: Application port for thermalmodelrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetBuildingThermalModelInput, GetBuildingThermalModelOutput } from "../dto/thermal-model.dto";
export interface ThermalModelRepository {
  getBuildingThermalModel(input: GetBuildingThermalModelInput): Promise<GetBuildingThermalModelOutput>;
}

export type { GetBuildingThermalModelInput, GetBuildingThermalModelOutput } from "../dto/thermal-model.dto";
