/**
 * Handlers for BindingConnection
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { NetworkDomainModule } from "../dependencies/network-ddd.dependencies.js";
import type { ListBindingConnectionConstraintsInput } from "@warmpact/services/network";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/network/binding-connections
 * Operation: listBindingConnectionConstraints
 */
export async function listBindingConnectionConstraints(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], networkZone?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: NetworkDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListBindingConnectionConstraintsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.bindingConnections.list.execute(input);
  return reply.code(200).send(result);
}


