/**
 * Handlers for ReturnTemperature
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { NetworkDomainModule } from "../dependencies/network-ddd.dependencies.js";
import type { IngestReturnTemperatureRecordInput, ListReturnTemperatureRecordsInput } from "@warmpact/services/network";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/network/return-temperatures
 * Operation: listReturnTemperatureRecords
 */
export async function listReturnTemperatureRecords(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], sortBy?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: NetworkDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListReturnTemperatureRecordsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.returnTemperatures.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/network/return-temperatures
 * Operation: ingestReturnTemperatureRecord
 */
export async function ingestReturnTemperatureRecord(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: NetworkDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: IngestReturnTemperatureRecordInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.returnTemperatures.get.execute(input);
  return reply.code(200).send(result);
}


