/**
 * Handlers for Setpoint
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { NetworkDomainModule } from "../dependencies/network-ddd.dependencies.js";
import type { IssueSupplyTemperatureSetpointInput, ListSupplyTemperatureSetpointsInput } from "@warmpact/services/network";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/network/setpoints
 * Operation: listSupplyTemperatureSetpoints
 */
export async function listSupplyTemperatureSetpoints(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { networkZone?: string | string[], cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: NetworkDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSupplyTemperatureSetpointsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.setpoints.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/network/setpoints
 * Operation: issueSupplyTemperatureSetpoint
 */
export async function issueSupplyTemperatureSetpoint(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: NetworkDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: IssueSupplyTemperatureSetpointInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.setpoints.get.execute(input);
  return reply.code(201).send(result);
}


