/**
 * ConditionReport DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConditionReport DTOs
 *
 * DDD: Application DTOs for ConditionReport use cases.
 */

import type { GetPlainLanguageConditionReportParams } from "@warmpact/core/advisory/types";

export type GetPlainLanguageConditionReportInput = GetPlainLanguageConditionReportParams;

export type GetPlainLanguageConditionReportOutput = {};
