/**
 * RemediationProposal DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RemediationProposal DTOs
 *
 * DDD: Application DTOs for RemediationProposal use cases.
 */

import type { IssueRemediationProposalRequestInput, ListRemediationProposalsParams } from "@warmpact/core/advisory/types";

export type ListRemediationProposalsInput = ListRemediationProposalsParams;

export type IssueRemediationProposalInput = IssueRemediationProposalRequestInput;

export type ListRemediationProposalsOutput = {};

export type IssueRemediationProposalOutput = {};
