/**
 * Underwriting DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: underwriting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Underwriting Domain Module - Composition root
 *
 * DDD: Composition root for underwriting domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ThermalModelRepositoryAdapter,
  UnderwritingRepositoryAdapter,
} from "@warmpact/adapters/underwriting";
import { getIdGeneratorService } from "@warmpact/adapters";
import type { AdapterDynamoDBClient } from "@warmpact/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetBuildingThermalModel,
  ExecuteGetUnderwritingAssessment,
  ExecuteUnderwriteBuildingConnection,
} from "@warmpact/services/underwriting/usecases";
// Ports (interfaces)
import type {
  ThermalModelRepository,
  UnderwritingRepository,
} from "@warmpact/services/underwriting/ports";

export interface UnderwritingDomainModule {
  repos: {
    thermalModels: ThermalModelRepository;
    underwritings: UnderwritingRepository;
  };
  useCases: {
    thermalModels: {
      get: ExecuteGetBuildingThermalModel;
    };
    underwritings: {
      get: ExecuteGetUnderwritingAssessment;
    };
  };
}

export function buildUnderwritingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): UnderwritingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      thermalModels?: ThermalModelRepository;
      underwritings?: UnderwritingRepository;
    } = {};

    obj.thermalModels = new ThermalModelRepositoryAdapter(dynamoClient);
    obj.underwritings = new UnderwritingRepositoryAdapter(dynamoClient);
    return {
      thermalModels: obj.thermalModels!,
      underwritings: obj.underwritings!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    thermalModels: {
      get: new ExecuteGetBuildingThermalModel(executionContext, idGenerator, repos.thermalModels),
    },
    underwritings: {
      get: new ExecuteGetUnderwritingAssessment(executionContext, idGenerator, repos.underwritings),
    },
  };
  return { repos, useCases: useCases as UnderwritingDomainModule["useCases"] };
}
