/**
 * Handlers for Underwriting
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: underwriting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { UnderwritingDomainModule } from "../dependencies/underwriting-ddd.dependencies.js";
import type { GetUnderwritingAssessmentInput, UnderwriteBuildingConnectionInput } from "@warmpact/services/underwriting";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/connections/{connectionId}/underwriting
 * Operation: underwriteBuildingConnection
 */
export async function underwriteBuildingConnection(
  request: FastifyRequest<{ Params: { connectionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: UnderwritingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UnderwriteBuildingConnectionInput = {
    connectionId: request.params.connectionId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.underwritings.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/connections/{connectionId}/underwriting
 * Operation: getUnderwritingAssessment
 */
export async function getUnderwritingAssessment(
  request: FastifyRequest<{ Params: { connectionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: UnderwritingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetUnderwritingAssessmentInput = {
    connectionId: request.params.connectionId,
  };
  const result = await deps.useCases.underwritings.get.execute(input);
  return reply.code(200).send(result);
}


