/**
 * SafetyFloor Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { SafetyFloorEntity } from "@warmpact/core/guarantees/models/index.js";
import { guaranteesSchemas } from "@warmpact/core/guarantees";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "grt";

export function createSafetyFloor(overrides: Partial<SafetyFloorEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    floorValue: overrides.floorValue ?? faker.number.int(),
    name: overrides.name ?? faker.person.fullName(),
    overridable: overrides.overridable ?? faker.datatype.boolean(),
    unit: overrides.unit ?? faker.lorem.word(),
    ...overrides,
  };

  return guaranteesSchemas.SafetyFloor.parse(raw);
}

export function safetyFloorBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSafetyFloor(overrides));
}
