/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { breachRoutes } from "./breach.routes.js";
export { conditionMeasurementRoutes } from "./condition-measurement.routes.js";
export { invoiceRoutes } from "./invoice.routes.js";
export { marginReportRoutes } from "./margin-report.routes.js";
