/**
 * Routes for MarginReport
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getMarginPerConnectionReport } from "../handlers/margin-report.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function marginReportRoutes(fastify: FastifyInstance) {
  // GET /v1/settlement/margin-report (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/settlement/margin-report",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSettlementDependenciesForRequest();
        await getMarginPerConnectionReport(request, reply, deps);
      });
    }
  );


}
