/**
 * Routes for ComparabilityCheck
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { checkPriceComparability } from "../handlers/comparability-check.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function comparabilityCheckRoutes(fastify: FastifyInstance) {
  // POST /v1/pricing/comparability-checks (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/pricing/comparability-checks",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPricingDependenciesForRequest();
        await checkPriceComparability(request, reply, deps);
      });
    }
  );


}
