/**
 * Forecasting DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: forecasting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Forecasting Domain Module - Composition root
 *
 * DDD: Composition root for forecasting domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DemandRepositoryAdapter,
} from "@warmpact/adapters/forecasting";
import { getIdGeneratorService } from "@warmpact/adapters";
import type { AdapterDynamoDBClient } from "@warmpact/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetDemandForecast,
} from "@warmpact/services/forecasting/usecases";
// Ports (interfaces)
import type {
  DemandRepository,
} from "@warmpact/services/forecasting/ports";

export interface ForecastingDomainModule {
  repos: {
    demands: DemandRepository;
  };
  useCases: {
    demands: {
      get: ExecuteGetDemandForecast;
    };
  };
}

export function buildForecastingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ForecastingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      demands?: DemandRepository;
    } = {};

    obj.demands = new DemandRepositoryAdapter(dynamoClient);
    return {
      demands: obj.demands!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    demands: {
      get: new ExecuteGetDemandForecast(executionContext, idGenerator, repos.demands),
    },
  };
  return { repos, useCases: useCases as ForecastingDomainModule["useCases"] };
}
