/**
 * WorkOrder Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { WorkOrderEntity } from "@warmpact/core/diagnostics/models/index.js";
import { diagnosticsSchemas } from "@warmpact/core/diagnostics";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "dia";

export function createWorkOrder(overrides: Partial<WorkOrderEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    connectionId: overrides.connectionId ?? faker.string.uuid(),
    findingId: overrides.findingId ?? faker.string.uuid(),
    priority: overrides.priority ?? "routine",
    status: overrides.status ?? "dispatched",
    ...overrides,
  };

  return diagnosticsSchemas.WorkOrder.parse(raw);
}

export function workOrderBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createWorkOrder(overrides));
}
