/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as advisoryRoutes from "../../domains/advisory/routes/index.js";
import * as customersRoutes from "../../domains/customers/routes/index.js";
import * as diagnosticsRoutes from "../../domains/diagnostics/routes/index.js";
import * as forecastingRoutes from "../../domains/forecasting/routes/index.js";
import * as governanceRoutes from "../../domains/governance/routes/index.js";
import * as guaranteesRoutes from "../../domains/guarantees/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as networkRoutes from "../../domains/network/routes/index.js";
import * as pricingRoutes from "../../domains/pricing/routes/index.js";
import * as settlementRoutes from "../../domains/settlement/routes/index.js";
import * as underwritingRoutes from "../../domains/underwriting/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "advisory", mod: advisoryRoutes },
  { domain: "customers", mod: customersRoutes },
  { domain: "diagnostics", mod: diagnosticsRoutes },
  { domain: "forecasting", mod: forecastingRoutes },
  { domain: "governance", mod: governanceRoutes },
  { domain: "guarantees", mod: guaranteesRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "network", mod: networkRoutes },
  { domain: "pricing", mod: pricingRoutes },
  { domain: "settlement", mod: settlementRoutes },
  { domain: "underwriting", mod: underwritingRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
