/**
 * Underwriting DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: underwriting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Underwriting DTOs
 *
 * DDD: Application DTOs for Underwriting use cases.
 */

import type { GetUnderwritingAssessmentParams, UnderwriteBuildingConnectionParams, UnderwriteBuildingConnectionRequestInput } from "@warmpact/core/underwriting/types";

export type UnderwriteBuildingConnectionInput = UnderwriteBuildingConnectionParams & UnderwriteBuildingConnectionRequestInput;

export type GetUnderwritingAssessmentInput = GetUnderwritingAssessmentParams;

export type UnderwriteBuildingConnectionOutput = {};

export type GetUnderwritingAssessmentOutput = {};
