/**
 * ExecuteGetUnderwritingAssessment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: underwriting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetUnderwritingAssessment Use Case
 *
 * DDD: Application use case for get Underwriting.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetUnderwritingAssessmentInput, GetUnderwritingAssessmentOutput } from "../dto/underwriting.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { UnderwritingRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetUnderwritingAssessment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly underwriting: UnderwritingRepository
  ) {}

  async execute(input: GetUnderwritingAssessmentInput): Promise<GetUnderwritingAssessmentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.uwrId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).connectionId) {
      throw new ValidationError("connectionId is required");
    }
    const connectionId = (input as any).connectionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.underwriting.getUnderwritingAssessment({ connectionId: connectionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${connectionId}`);
    }

    return entity as GetUnderwritingAssessmentOutput;
  }
}
