/**
 * Routes for ReturnTemperature
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { ingestReturnTemperatureRecord, listReturnTemperatureRecords } from "../handlers/return-temperature.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function returnTemperatureRoutes(fastify: FastifyInstance) {
  // POST /v1/network/return-temperatures (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/network/return-temperatures",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getNetworkDependenciesForRequest();
        await ingestReturnTemperatureRecord(request, reply, deps);
      });
    }
  );


  // GET /v1/network/return-temperatures (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/network/return-temperatures",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getNetworkDependenciesForRequest();
        await listReturnTemperatureRecords(request, reply, deps);
      });
    }
  );


}
