/**
 * Network DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Network Domain Module - Composition root
 *
 * DDD: Composition root for network domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ReturnTemperatureRepositoryAdapter,
  SetpointRepositoryAdapter,
} from "@warmpact/adapters/network";
import { getIdGeneratorService } from "@warmpact/adapters";
import type { AdapterDynamoDBClient } from "@warmpact/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteIngestReturnTemperatureRecord,
  ExecuteIssueSupplyTemperatureSetpoint,
  ExecuteListBindingConnectionConstraints,
  ExecuteListReturnTemperatureRecords,
  ExecuteListSupplyTemperatureSetpoints,
} from "@warmpact/services/network/usecases";
// Ports (interfaces)
import type {
  ReturnTemperatureRepository,
  SetpointRepository,
} from "@warmpact/services/network/ports";

export interface NetworkDomainModule {
  repos: {
    returnTemperatures: ReturnTemperatureRepository;
    setpoints: SetpointRepository;
  };
  useCases: {
    returnTemperatures: {
      get: ExecuteIngestReturnTemperatureRecord;
      list: ExecuteListReturnTemperatureRecords;
    };
    setpoints: {
      get: ExecuteIssueSupplyTemperatureSetpoint;
      list: ExecuteListSupplyTemperatureSetpoints;
    };
  };
}

export function buildNetworkDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): NetworkDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      returnTemperatures?: ReturnTemperatureRepository;
      setpoints?: SetpointRepository;
    } = {};

    obj.returnTemperatures = new ReturnTemperatureRepositoryAdapter(dynamoClient);
    obj.setpoints = new SetpointRepositoryAdapter(dynamoClient);
    return {
      returnTemperatures: obj.returnTemperatures!,
      setpoints: obj.setpoints!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    returnTemperatures: {
      get: new ExecuteIngestReturnTemperatureRecord(executionContext, idGenerator, repos.returnTemperatures),
      list: new ExecuteListReturnTemperatureRecords(executionContext, idGenerator, repos.returnTemperatures),
    },
    setpoints: {
      get: new ExecuteIssueSupplyTemperatureSetpoint(executionContext, idGenerator, repos.setpoints),
      list: new ExecuteListSupplyTemperatureSetpoints(executionContext, idGenerator, repos.setpoints),
    },
  };
  return { repos, useCases: useCases as NetworkDomainModule["useCases"] };
}
