/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: underwriting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { thermalModelRoutes } from "./thermal-model.routes.js";
export { underwritingRoutes } from "./underwriting.routes.js";
