/**
 * CarbonIntensity DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CarbonIntensity DTOs
 *
 * DDD: Application DTOs for CarbonIntensity use cases.
 */

import type { ListCarbonIntensityRecordsParams } from "@warmpact/core/governance/types";

export type ListCarbonIntensityRecordsInput = ListCarbonIntensityRecordsParams;

export type ListCarbonIntensityRecordsOutput = {};
