/**
 * FaultFinding Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/diagnostics.openapi.types.js";
import { schemas } from "../schemas/diagnostics.schemas.js";

/**
 * Entity: FaultFindingEntity
 * Description: Represents the FaultFinding domain model.
 * Source: schemas.FaultFinding
 * Type: Domain Entity (API)
 */
export const FaultFindingEntitySchema = schemas.FaultFinding;
export type FaultFindingEntity = components["schemas"]["FaultFinding"];
