/**
 * Models barrel export - All Diagnostics entities
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./fault-finding.entity.js";
export * from "./work-order.entity.js";
