/**
 * SwitchRiskSignal Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { SwitchRiskSignalEntity } from "@warmpact/core/customers/models/index.js";
import { customersSchemas } from "@warmpact/core/customers";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cst";

export function createSwitchRiskSignal(overrides: Partial<SwitchRiskSignalEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    customerId: overrides.customerId ?? faker.string.uuid(),
    riskLevel: overrides.riskLevel ?? "low",
    signals: overrides.signals ?? [],
    ...overrides,
  };

  return customersSchemas.SwitchRiskSignal.parse(raw);
}

export function switchRiskSignalBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSwitchRiskSignal(overrides));
}
