/**
 * Handlers for Customer
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CustomersDomainModule } from "../dependencies/customers-ddd.dependencies.js";
import type { ListHeatCustomersInput } from "@warmpact/services/customers";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/customers
 * Operation: listHeatCustomers
 */
export async function listHeatCustomers(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], segment?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CustomersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListHeatCustomersInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.customers.list.execute(input);
  return reply.code(200).send(result);
}


