/**
 * CheckPriceComparability handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { checkPriceComparability } from "@warmpact/api-server/domains/pricing/handlers";
import type { PricingDDDDependencies } from "@warmpact/api-server/domains/pricing";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@warmpact/tests/shared";
import { PRICING_USE_CASES } from "../__factories__/use-cases.js";

describe("CheckPriceComparability", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PricingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PricingDDDDependencies>(
      PRICING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCheckPriceComparability, "execute").mockResolvedValue(useCaseResult);

    await checkPriceComparability(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCheckPriceComparability.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
