/**
 * ExecuteListGovernanceEvents - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListGovernanceEvents Use Case
 *
 * DDD: Application use case for list Event.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListGovernanceEventsInput, ListGovernanceEventsOutput } from "../dto/event.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { EventRepository } from "../ports";

export class ExecuteListGovernanceEvents {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly event: EventRepository
  ) {}

  async execute(input: ListGovernanceEventsInput): Promise<ListGovernanceEventsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.event.listGovernanceEvents({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListGovernanceEventsOutput;
  }
}
