/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { customerRoutes } from "./customer.routes.js";
export { switchRiskSignalRoutes } from "./switch-risk-signal.routes.js";
export { connectionRoutes } from "./connection.routes.js";
