/**
 * Repository interface for ConditionProduct
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ConditionProductEntity
} from "../models/condition-product.entity.js";
import type {
  ConditionProduct
} from "../types/index.js";
/**
 * ConditionProductRepository Interface
 */
export interface ConditionProductRepository extends CreateReadRepository<ConditionProductEntity, ConditionProduct, string, Record<string, never>> {

}
