/**
 * Repository interface for ExitPackage
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ExitPackageEntity
} from "../models/exit-package.entity.js";
import type {
  ExitPackage
} from "../types/index.js";
/**
 * ExitPackageRepository Interface
 */
export interface ExitPackageRepository extends CreateReadRepository<ExitPackageEntity, ExitPackage, string, Record<string, never>> {

}
