/**
 * Repository interface for SafetyFloor
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SafetyFloorEntity
} from "../models/safety-floor.entity.js";
/**
 * SafetyFloorRepository Interface
 */
export interface SafetyFloorRepository extends ReadRepository<SafetyFloorEntity, string, Record<string, never>> {

}
