/**
 * SwitchRiskSignalRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SwitchRiskSignalRepository Port
 *
 * DDD: Application port for switchrisksignalrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListSwitchRiskSignalsInput, ListSwitchRiskSignalsOutput } from "../dto/switch-risk-signal.dto";
export interface SwitchRiskSignalRepository {
  listSwitchRiskSignals(input: ListSwitchRiskSignalsInput): Promise<ListSwitchRiskSignalsOutput>;
}

export type { ListSwitchRiskSignalsInput, ListSwitchRiskSignalsOutput } from "../dto/switch-risk-signal.dto";
