/**
 * UnderwriteBuildingConnection handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: underwriting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { underwriteBuildingConnection } from "@warmpact/api-server/domains/underwriting/handlers";
import type { UnderwritingDDDDependencies } from "@warmpact/api-server/domains/underwriting";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@warmpact/tests/shared";
import { UNDERWRITING_USE_CASES } from "../__factories__/use-cases.js";

describe("UnderwriteBuildingConnection", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: UnderwritingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<UnderwritingDDDDependencies>(
      UNDERWRITING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUnderwriteBuildingConnection, "execute").mockResolvedValue(useCaseResult);

    await underwriteBuildingConnection(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUnderwriteBuildingConnection.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
