/**
 * ListInvoice DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListFlatRateInvoicesParams } from "@warmpact/core/settlement";

export function createListInvoiceRequest(overrides: Partial<ListFlatRateInvoicesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
