/**
 * RevisionTrigger Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { RevisionTriggerEntity } from "@warmpact/core/pricing/models/index.js";
import { pricingSchemas } from "@warmpact/core/pricing";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prc";

export function createRevisionTrigger(overrides: Partial<RevisionTriggerEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    dueOn: overrides.dueOn ?? faker.date.anytime().toISOString().split('T')[0],
    guaranteeId: overrides.guaranteeId ?? faker.string.uuid(),
    status: overrides.status ?? "due",
    trigger: overrides.trigger ?? "fuel_price_band",
    ...overrides,
  };

  return pricingSchemas.RevisionTrigger.parse(raw);
}

export function revisionTriggerBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRevisionTrigger(overrides));
}
