/**
 * Handlers for FlatRate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PricingDomainModule } from "../dependencies/pricing-ddd.dependencies.js";
import type { BuildFlatRatePriceInput } from "@warmpact/services/pricing";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/pricing/flat-rates
 * Operation: buildFlatRatePrice
 */
export async function buildFlatRatePrice(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: PricingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: BuildFlatRatePriceInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.flatRates.get.execute(input);
  return reply.code(200).send(result);
}


