/**
 * Handlers for RevisionTrigger
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PricingDomainModule } from "../dependencies/pricing-ddd.dependencies.js";
import type { ListRevisionTriggersInput } from "@warmpact/services/pricing";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/pricing/revision-triggers
 * Operation: listRevisionTriggers
 */
export async function listRevisionTriggers(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PricingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListRevisionTriggersInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.revisionTriggers.list.execute(input);
  return reply.code(200).send(result);
}


