/**
 * BindingConnection DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BindingConnection DTOs
 *
 * DDD: Application DTOs for BindingConnection use cases.
 */

import type { ListBindingConnectionConstraintsParams } from "@warmpact/core/network/types";

export type ListBindingConnectionConstraintsInput = ListBindingConnectionConstraintsParams;

export type ListBindingConnectionConstraintsOutput = {};
