/**
 * ReturnTemperature DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReturnTemperature DTOs
 *
 * DDD: Application DTOs for ReturnTemperature use cases.
 */

import type { IngestReturnTemperatureRecordRequestInput, ListReturnTemperatureRecordsParams } from "@warmpact/core/network/types";

export type ListReturnTemperatureRecordsInput = ListReturnTemperatureRecordsParams;

export type IngestReturnTemperatureRecordInput = IngestReturnTemperatureRecordRequestInput;

export type ListReturnTemperatureRecordsOutput = {};

export type IngestReturnTemperatureRecordOutput = {};
