/**
 * Setpoint DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Setpoint DTOs
 *
 * DDD: Application DTOs for Setpoint use cases.
 */

import type { IssueSupplyTemperatureSetpointRequestInput, ListSupplyTemperatureSetpointsParams } from "@warmpact/core/network/types";

export type ListSupplyTemperatureSetpointsInput = ListSupplyTemperatureSetpointsParams;

export type IssueSupplyTemperatureSetpointInput = IssueSupplyTemperatureSetpointRequestInput;

export type ListSupplyTemperatureSetpointsOutput = {};

export type IssueSupplyTemperatureSetpointOutput = {};
