/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the diagnostics domain.
 * Use these factories in tests to create test data.
 */

export { createFaultFinding } from "./fault-finding/entity/fault-finding.entity.factory.js";
export { createWorkOrder } from "./work-order/entity/work-order.entity.factory.js";
