/**
 * ReleaseExitPackage handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { releaseExitPackage } from "@warmpact/api-server/domains/guarantees/handlers";
import type { GuaranteesDDDDependencies } from "@warmpact/api-server/domains/guarantees";
import { createExitPackage as createExitPackageEntity } from "@warmpact/factories/guarantees";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@warmpact/tests/shared";
import { GUARANTEES_USE_CASES } from "../__factories__/use-cases.js";

describe("ReleaseExitPackage", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GuaranteesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GuaranteesDDDDependencies>(
      GUARANTEES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createExitPackageEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeReleaseExitPackage, "execute").mockResolvedValue(useCaseResult);

    await releaseExitPackage(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeReleaseExitPackage.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
