/**
 * ExitPackage DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExitPackage DTOs
 *
 * DDD: Application DTOs for ExitPackage use cases.
 */

import type { ReleaseExitPackageParams, ReleaseExitPackageRequestInput } from "@warmpact/core/guarantees/types";

export type ReleaseExitPackageInput = ReleaseExitPackageParams & ReleaseExitPackageRequestInput;

export type ReleaseExitPackageOutput = {};
