/**
 * OverrideAttempt DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OverrideAttempt DTOs
 *
 * DDD: Application DTOs for OverrideAttempt use cases.
 */

import type { AttemptSafetyFloorOverrideRequestInput } from "@warmpact/core/guarantees/types";

export type AttemptSafetyFloorOverrideInput = AttemptSafetyFloorOverrideRequestInput;

export type AttemptSafetyFloorOverrideOutput = {};
