/**
 * SafetyFloor DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SafetyFloor DTOs
 *
 * DDD: Application DTOs for SafetyFloor use cases.
 */

export type GetSafetyFloorsInput = {};

export type GetSafetyFloorsOutput = {};
