/**
 * ConditionMeasurement DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConditionMeasurement DTOs
 *
 * DDD: Application DTOs for ConditionMeasurement use cases.
 */

import type { IngestConditionMeasurementRequestInput } from "@warmpact/core/settlement/types";

export type IngestConditionMeasurementInput = IngestConditionMeasurementRequestInput;

export type IngestConditionMeasurementOutput = {};
