/**
 * MarginReport DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MarginReport DTOs
 *
 * DDD: Application DTOs for MarginReport use cases.
 */

import type { GetMarginPerConnectionReportParams } from "@warmpact/core/settlement/types";

export type GetMarginPerConnectionReportInput = GetMarginPerConnectionReportParams;

export type GetMarginPerConnectionReportOutput = {};
