/**
 * RemediationProposal Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { RemediationProposalEntity } from "@warmpact/core/advisory/models/index.js";
import { advisorySchemas } from "@warmpact/core/advisory";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "adv";

export function createRemediationProposal(overrides: Partial<RemediationProposalEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    connectionId: overrides.connectionId ?? faker.string.uuid(),
    measures: overrides.measures ?? [],
    status: overrides.status ?? "drafted",
    ...overrides,
  };

  return advisorySchemas.RemediationProposal.parse(raw);
}

export function remediationProposalBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRemediationProposal(overrides));
}
