/**
 * SwitchRiskSignal Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/customers.openapi.types.js";
import { schemas } from "../schemas/customers.schemas.js";

/**
 * Entity: SwitchRiskSignalEntity
 * Description: Represents the SwitchRiskSignal domain model.
 * Source: schemas.SwitchRiskSignal
 * Type: Domain Entity (API)
 */
export const SwitchRiskSignalEntitySchema = schemas.SwitchRiskSignal;
export type SwitchRiskSignalEntity = components["schemas"]["SwitchRiskSignal"];
