/**
 * ConditionMeasurementRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConditionMeasurementRepository Port
 *
 * DDD: Application port for conditionmeasurementrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { IngestConditionMeasurementInput, IngestConditionMeasurementOutput } from "../dto/condition-measurement.dto";
export interface ConditionMeasurementRepository {
  ingestConditionMeasurement(input: IngestConditionMeasurementInput): Promise<IngestConditionMeasurementOutput>;
}

export type { IngestConditionMeasurementInput, IngestConditionMeasurementOutput } from "../dto/condition-measurement.dto";
