/**
 * MarginReportClient Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MarginReportClient Port
 *
 * DDD: Application port for marginreportclient operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetMarginPerConnectionReportInput, GetMarginPerConnectionReportOutput } from "../dto/margin-report.dto";
export interface MarginReportClient {
  getMarginPerConnectionReport(input: GetMarginPerConnectionReportInput): Promise<GetMarginPerConnectionReportOutput>;
}

export type { GetMarginPerConnectionReportInput, GetMarginPerConnectionReportOutput } from "../dto/margin-report.dto";
