/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Customers Domain Use Cases
 * 
 * List of all use case names for the customers domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CUSTOMERS_USE_CASES = [
  "executeGetBuildingConnection",
  "executeListBuildingConnections",
  "executeListHeatCustomers",
  "executeListSwitchRiskSignals",
  "executeRegisterBuildingConnection"
] as const;
