/**
 * Repository interface for FaultFinding
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  FaultFindingEntity
} from "../models/fault-finding.entity.js";
import type {
  ListFaultFindingsParams
} from "../types/index.js";
/**
 * FaultFindingRepository Interface
 */
export interface FaultFindingRepository extends ReadRepository<FaultFindingEntity, string, ListFaultFindingsParams> {

}
