/**
 * Demand DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: forecasting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Demand DTOs
 *
 * DDD: Application DTOs for Demand use cases.
 */

import type { GetDemandForecastParams } from "@warmpact/core/forecasting/types";

export type GetDemandForecastInput = GetDemandForecastParams;

export type GetDemandForecastOutput = {};
