/**
 * DispatchWorkOrder handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { dispatchWorkOrder } from "@warmpact/api-server/domains/diagnostics/handlers";
import type { DiagnosticsDDDDependencies } from "@warmpact/api-server/domains/diagnostics";
import { createWorkOrder as createWorkOrderEntity } from "@warmpact/factories/diagnostics";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@warmpact/tests/shared";
import { DIAGNOSTICS_USE_CASES } from "../__factories__/use-cases.js";

describe("DispatchWorkOrder", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DiagnosticsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DiagnosticsDDDDependencies>(
      DIAGNOSTICS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createWorkOrderEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeDispatchWorkOrder, "execute").mockResolvedValue(useCaseResult);

    await dispatchWorkOrder(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeDispatchWorkOrder.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
