/**
 * GetBuildingConnection handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getBuildingConnection } from "@warmpact/api-server/domains/customers/handlers";
import type { CustomersDDDDependencies } from "@warmpact/api-server/domains/customers";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@warmpact/tests/shared";
import { CUSTOMERS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetBuildingConnection", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CustomersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CustomersDDDDependencies>(
      CUSTOMERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetBuildingConnection, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { connectionId: entity.id };

    await getBuildingConnection(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetBuildingConnection.execute).toHaveBeenCalledWith(expect.objectContaining({ connectionId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { connectionId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetBuildingConnection, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getBuildingConnection(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
