/**
 * ConditionMeasurementRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConditionMeasurementRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConditionMeasurementRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConditionMeasurementRepository,
} from "@warmpact/services/settlement";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConditionMeasurementRepositoryDdb } from "./condition-measurement-repository.ddb.js";

/**
 * ConditionMeasurementRepositoryAdapter
 *
 * Implements ConditionMeasurementRepository port for infrastructure layer.
 */
export class ConditionMeasurementRepositoryAdapter implements ConditionMeasurementRepository {
  private readonly ddb: ConditionMeasurementRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConditionMeasurementRepositoryDdb(this.dynamoClient);
  }

  async ingestConditionMeasurement(input: Parameters<ConditionMeasurementRepository['ingestConditionMeasurement']>[0]): Promise<Awaited<ReturnType<ConditionMeasurementRepository['ingestConditionMeasurement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.ingestConditionMeasurement(input);
  }
}
