/**
 * InvoiceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InvoiceRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements InvoiceRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  InvoiceRepository,
} from "@warmpact/services/settlement";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { InvoiceRepositoryDdb } from "./invoice-repository.ddb.js";

/**
 * InvoiceRepositoryAdapter
 *
 * Implements InvoiceRepository port for infrastructure layer.
 */
export class InvoiceRepositoryAdapter implements InvoiceRepository {
  private readonly ddb: InvoiceRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new InvoiceRepositoryDdb(this.dynamoClient);
  }

  async listFlatRateInvoices(input: Parameters<InvoiceRepository['listFlatRateInvoices']>[0]): Promise<Awaited<ReturnType<InvoiceRepository['listFlatRateInvoices']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFlatRateInvoices(input);
  }

  async issueFlatRateInvoice(input: Parameters<InvoiceRepository['issueFlatRateInvoice']>[0]): Promise<Awaited<ReturnType<InvoiceRepository['issueFlatRateInvoice']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.issueFlatRateInvoice(input);
  }
}
