/**
 * ExitPackage Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/guarantees.openapi.types.js";
import { schemas } from "../schemas/guarantees.schemas.js";

/**
 * Entity: ExitPackageEntity
 * Description: Represents the ExitPackage domain model.
 * Source: schemas.ExitPackage
 * Type: Domain Entity (API)
 */
export const ExitPackageEntitySchema = schemas.ExitPackage;
export type ExitPackageEntity = components["schemas"]["ExitPackage"];
