/**
 * SafetyFloor Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/guarantees.openapi.types.js";
import { schemas } from "../schemas/guarantees.schemas.js";

/**
 * Entity: SafetyFloorEntity
 * Description: Represents the SafetyFloor domain model.
 * Source: schemas.SafetyFloor
 * Type: Domain Entity (API)
 */
export const SafetyFloorEntitySchema = schemas.SafetyFloor;
export type SafetyFloorEntity = components["schemas"]["SafetyFloor"];
