/**
 * FaultFindingRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FaultFindingRepository Port
 *
 * DDD: Application port for faultfindingrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListFaultFindingsInput, ListFaultFindingsOutput } from "../dto/fault-finding.dto";
export interface FaultFindingRepository {
  listFaultFindings(input: ListFaultFindingsInput): Promise<ListFaultFindingsOutput>;
}

export type { ListFaultFindingsInput, ListFaultFindingsOutput } from "../dto/fault-finding.dto";
