/**
 * WorkOrderRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WorkOrderRepository Port
 *
 * DDD: Application port for workorderrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DispatchWorkOrderInput, DispatchWorkOrderOutput } from "../dto/work-order.dto";
export interface WorkOrderRepository {
  dispatchWorkOrder(input: DispatchWorkOrderInput): Promise<DispatchWorkOrderOutput>;
}

export type { DispatchWorkOrderInput, DispatchWorkOrderOutput } from "../dto/work-order.dto";
