/**
 * Handlers for Demand
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: forecasting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ForecastingDomainModule } from "../dependencies/forecasting-ddd.dependencies.js";
import type { GetDemandForecastInput } from "@warmpact/services/forecasting";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/forecasts/demand
 * Operation: getDemandForecast
 */
export async function getDemandForecast(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { connectionId?: string | string[], networkZone?: string | string[], horizonHours?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ForecastingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDemandForecastInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.demands.get.execute(input);
  return reply.code(200).send(result);
}


