/**
 * Handlers for ConditionReport
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AdvisoryDomainModule } from "../dependencies/advisory-ddd.dependencies.js";
import type { GetPlainLanguageConditionReportInput } from "@warmpact/services/advisory";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/advisory/condition-reports
 * Operation: getPlainLanguageConditionReport
 */
export async function getPlainLanguageConditionReport(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { connectionId?: string | string[], period?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AdvisoryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPlainLanguageConditionReportInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.conditionReports.get.execute(input);
  return reply.code(200).send(result);
}


