/**
 * Handlers for RemediationProposal
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AdvisoryDomainModule } from "../dependencies/advisory-ddd.dependencies.js";
import type { IssueRemediationProposalInput, ListRemediationProposalsInput } from "@warmpact/services/advisory";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/advisory/remediation-proposals
 * Operation: listRemediationProposals
 */
export async function listRemediationProposals(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AdvisoryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListRemediationProposalsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.remediationProposals.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/advisory/remediation-proposals
 * Operation: issueRemediationProposal
 */
export async function issueRemediationProposal(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AdvisoryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: IssueRemediationProposalInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.remediationProposals.get.execute(input);
  return reply.code(201).send(result);
}


