/**
 * ComparabilityCheckRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComparabilityCheckRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ComparabilityCheckRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ComparabilityCheckRepository,
} from "@warmpact/services/pricing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ComparabilityCheckRepositoryDdb } from "./comparability-check-repository.ddb.js";

/**
 * ComparabilityCheckRepositoryAdapter
 *
 * Implements ComparabilityCheckRepository port for infrastructure layer.
 */
export class ComparabilityCheckRepositoryAdapter implements ComparabilityCheckRepository {
  private readonly ddb: ComparabilityCheckRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ComparabilityCheckRepositoryDdb(this.dynamoClient);
  }

  async checkPriceComparability(input: Parameters<ComparabilityCheckRepository['checkPriceComparability']>[0]): Promise<Awaited<ReturnType<ComparabilityCheckRepository['checkPriceComparability']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.checkPriceComparability(input);
  }
}
