/**
 * FlatRateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FlatRateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FlatRateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FlatRateRepository,
} from "@warmpact/services/pricing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FlatRateRepositoryDdb } from "./flat-rate-repository.ddb.js";

/**
 * FlatRateRepositoryAdapter
 *
 * Implements FlatRateRepository port for infrastructure layer.
 */
export class FlatRateRepositoryAdapter implements FlatRateRepository {
  private readonly ddb: FlatRateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FlatRateRepositoryDdb(this.dynamoClient);
  }

  async buildFlatRatePrice(input: Parameters<FlatRateRepository['buildFlatRatePrice']>[0]): Promise<Awaited<ReturnType<FlatRateRepository['buildFlatRatePrice']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.buildFlatRatePrice(input);
  }
}
