/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./comparability-check-repository.ddb.js";
export * from "./flat-rate-repository.ddb.js";
export * from "./revision-trigger-repository.ddb.js";
export * from "./comparability-check-repository.adapter.js";
export * from "./flat-rate-repository.adapter.js";
export * from "./revision-trigger-repository.adapter.js";
