/**
 * ListFaultFindings handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listFaultFindings } from "@warmpact/api-server/domains/diagnostics/handlers";
import type { DiagnosticsDDDDependencies } from "@warmpact/api-server/domains/diagnostics";
import { createFaultFinding as createFaultFindingEntity } from "@warmpact/factories/diagnostics";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@warmpact/tests/shared";
import { DIAGNOSTICS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListFaultFindings", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DiagnosticsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DiagnosticsDDDDependencies>(
      DIAGNOSTICS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createFaultFindingEntity({ orgId }),
      createFaultFindingEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListFaultFindings, "execute").mockResolvedValue(useCaseResult);

    await listFaultFindings(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListFaultFindings.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
