/**
 * IssueRemediationProposal handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { issueRemediationProposal } from "@warmpact/api-server/domains/advisory/handlers";
import type { AdvisoryDDDDependencies } from "@warmpact/api-server/domains/advisory";
import { createRemediationProposal as createRemediationProposalEntity } from "@warmpact/factories/advisory";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@warmpact/tests/shared";
import { ADVISORY_USE_CASES } from "../__factories__/use-cases.js";

describe("IssueRemediationProposal", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AdvisoryDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AdvisoryDDDDependencies>(
      ADVISORY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createRemediationProposalEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeIssueRemediationProposal, "execute").mockResolvedValue(useCaseResult);

    await issueRemediationProposal(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeIssueRemediationProposal.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
