/**
 * Pricing Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const buildFlatRatePrice_Body = z
  .object({
    connectionId: z.string(),
    conditionProductId: z.string(),
    degreeDayNormalYear: z.number().int().optional(),
    carbonPricePerTonne: z
      .object({ amount: z.number(), currency: z.string() })
      .passthrough()
      .optional(),
  })
  .passthrough();

export const schemas: any = {
  buildFlatRatePrice_Body,
};

const endpoints = makeApi([
  {
    method: 'post',
    path: '/v1/pricing/comparability-checks',
    alias: 'checkPriceComparability',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: z.object({ guaranteeId: z.string() }).passthrough(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            guaranteeId: z.string(),
            verdict: z.enum([
              'comparable',
              'deviation_justified',
              'deviation_unjustified',
            ]),
            cohortDefinition: z.string().optional(),
            cohortSize: z.number().int().optional(),
            medianCohortRate: z
              .object({ amount: z.number(), currency: z.string() })
              .passthrough()
              .optional(),
            deviationPercent: z.number().optional(),
            publishedTariffReference: z.string().optional(),
            justification: z.string().optional(),
            reviewedBy: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/pricing/flat-rates',
    alias: 'buildFlatRatePrice',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: buildFlatRatePrice_Body,
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string(),
            connectionId: z.string(),
            flatMonthlyRate: z
              .object({ amount: z.number(), currency: z.string() })
              .passthrough(),
            components: z.array(
              z
                .object({
                  component: z.enum([
                    'modelled_heat_cost',
                    'fuel_and_carbon',
                    'distribution_and_heat_loss',
                    'substation_service',
                    'guarantee_risk_margin',
                    'advisory_service',
                    'platform_and_administration',
                  ]),
                  amount: z
                    .object({ amount: z.number(), currency: z.string() })
                    .passthrough(),
                  plainLanguage: z.string().optional(),
                })
                .passthrough()
            ),
            degreeDayNormalYear: z.number().int().optional(),
            revisionTriggers: z
              .array(
                z.enum([
                  'fuel_price_band',
                  'carbon_price_band',
                  'degree_day_deviation',
                  'building_renovation',
                  'term_anniversary',
                ])
              )
              .optional(),
            customerAnnualExpenditureEstimate: z
              .object({ amount: z.number(), currency: z.string() })
              .passthrough()
              .optional(),
            comparedToMeteredTariff: z
              .object({ amount: z.number(), currency: z.string() })
              .passthrough()
              .optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/pricing/revision-triggers',
    alias: 'listRevisionTriggers',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z
          .enum(['due', 'in_progress', 'completed', 'waived'])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string(),
                  guaranteeId: z.string(),
                  connectionId: z.string().optional(),
                  trigger: z.enum([
                    'fuel_price_band',
                    'carbon_price_band',
                    'degree_day_deviation',
                    'building_renovation',
                    'term_anniversary',
                  ]),
                  status: z.enum(['due', 'in_progress', 'completed', 'waived']),
                  dueOn: z.string(),
                })
                .passthrough()
            ),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
