/**
 * GetDemand DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: forecasting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetDemandForecastParams } from "@warmpact/core/forecasting";

export function createGetDemandRequest(overrides: Partial<GetDemandForecastParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
