/**
 * WorkOrder DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WorkOrder DTOs
 *
 * DDD: Application DTOs for WorkOrder use cases.
 */

import type { DispatchWorkOrderParams, DispatchWorkOrderRequestInput } from "@warmpact/core/diagnostics/types";

export type DispatchWorkOrderInput = DispatchWorkOrderParams & DispatchWorkOrderRequestInput;

export type DispatchWorkOrderOutput = {};
