/**
 * Handlers for ConditionMeasurement
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SettlementDomainModule } from "../dependencies/settlement-ddd.dependencies.js";
import type { IngestConditionMeasurementInput } from "@warmpact/services/settlement";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/settlement/condition-measurements
 * Operation: ingestConditionMeasurement
 */
export async function ingestConditionMeasurement(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: SettlementDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: IngestConditionMeasurementInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.conditionMeasurements.get.execute(input);
  return reply.code(200).send(result);
}


