/**
 * Handlers for MarginReport
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SettlementDomainModule } from "../dependencies/settlement-ddd.dependencies.js";
import type { GetMarginPerConnectionReportInput } from "@warmpact/services/settlement";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/settlement/margin-report
 * Operation: getMarginPerConnectionReport
 */
export async function getMarginPerConnectionReport(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { period?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SettlementDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetMarginPerConnectionReportInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.marginReports.get.execute(input);
  return reply.code(200).send(result);
}


