/**
 * Routes for WorkOrder
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { dispatchWorkOrder } from "../handlers/work-order.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function workOrderRoutes(fastify: FastifyInstance) {
  // POST /v1/diagnostics/fault-findings/{findingId}/work-order (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/diagnostics/fault-findings/:findingId/work-order",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { findingId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDiagnosticsDependenciesForRequest();
        await dispatchWorkOrder(request, reply, deps);
      });
    }
  );


}
