/**
 * ComparabilityCheckRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComparabilityCheckRepository Port
 *
 * DDD: Application port for comparabilitycheckrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CheckPriceComparabilityInput, CheckPriceComparabilityOutput } from "../dto/comparability-check.dto";
export interface ComparabilityCheckRepository {
  checkPriceComparability(input: CheckPriceComparabilityInput): Promise<CheckPriceComparabilityOutput>;
}

export type { CheckPriceComparabilityInput, CheckPriceComparabilityOutput } from "../dto/comparability-check.dto";
