/**
 * RevisionTriggerRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RevisionTriggerRepository Port
 *
 * DDD: Application port for revisiontriggerrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListRevisionTriggersInput, ListRevisionTriggersOutput } from "../dto/revision-trigger.dto";
export interface RevisionTriggerRepository {
  listRevisionTriggers(input: ListRevisionTriggersInput): Promise<ListRevisionTriggersOutput>;
}

export type { ListRevisionTriggersInput, ListRevisionTriggersOutput } from "../dto/revision-trigger.dto";
