/**
 * ExecuteListRemediationProposals - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListRemediationProposals Use Case
 *
 * DDD: Application use case for list RemediationProposal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListRemediationProposalsInput, ListRemediationProposalsOutput } from "../dto/remediation-proposal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { RemediationProposalRepository } from "../ports";

export class ExecuteListRemediationProposals {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly remediationProposal: RemediationProposalRepository
  ) {}

  async execute(input: ListRemediationProposalsInput): Promise<ListRemediationProposalsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.advId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.remediationProposal.listRemediationProposals({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListRemediationProposalsOutput;
  }
}
