/**
 * ExecuteIssueRemediationProposal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteIssueRemediationProposal Use Case
 *
 * DDD: Application use case for get RemediationProposal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { IssueRemediationProposalInput, IssueRemediationProposalOutput } from "../dto/remediation-proposal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { RemediationProposalRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteIssueRemediationProposal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly remediationProposal: RemediationProposalRepository
  ) {}

  async execute(input: IssueRemediationProposalInput): Promise<IssueRemediationProposalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.advId();

    // All field names extracted from OpenAPI spec: benchmarkCohortId, connectionId, measures
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).benchmarkCohortId) {
      throw new ValidationError("benchmarkCohortId is required");
    }
    const benchmarkcohortId = (input as any).benchmarkCohortId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.remediationProposal.issueRemediationProposal({ benchmarkCohortId: benchmarkcohortId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${benchmarkcohortId}`);
    }

    return entity as IssueRemediationProposalOutput;
  }
}
