/**
 * FaultFindingRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FaultFindingRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FaultFindingRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FaultFindingRepository,
} from "@warmpact/services/diagnostics";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FaultFindingRepositoryDdb } from "./fault-finding-repository.ddb.js";

/**
 * FaultFindingRepositoryAdapter
 *
 * Implements FaultFindingRepository port for infrastructure layer.
 */
export class FaultFindingRepositoryAdapter implements FaultFindingRepository {
  private readonly ddb: FaultFindingRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FaultFindingRepositoryDdb(this.dynamoClient);
  }

  async listFaultFindings(input: Parameters<FaultFindingRepository['listFaultFindings']>[0]): Promise<Awaited<ReturnType<FaultFindingRepository['listFaultFindings']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFaultFindings(input);
  }
}
