/**
 * RemediationProposal Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/advisory.openapi.types.js";
import { schemas } from "../schemas/advisory.schemas.js";

/**
 * Entity: RemediationProposalEntity
 * Description: Represents the RemediationProposal domain model.
 * Source: schemas.RemediationProposal
 * Type: Domain Entity (API)
 */
export const RemediationProposalEntitySchema = schemas.RemediationProposal;
export type RemediationProposalEntity = components["schemas"]["RemediationProposal"];
