/**
 * Customers DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Customers Domain Module - Composition root
 *
 * DDD: Composition root for customers domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CustomerRepositoryAdapter,
  SwitchRiskSignalRepositoryAdapter,
} from "@warmpact/adapters/customers";
import { getIdGeneratorService } from "@warmpact/adapters";
import type { AdapterDynamoDBClient } from "@warmpact/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetBuildingConnection,
  ExecuteListBuildingConnections,
  ExecuteListHeatCustomers,
  ExecuteListSwitchRiskSignals,
  ExecuteRegisterBuildingConnection,
} from "@warmpact/services/customers/usecases";
// Ports (interfaces)
import type {
  CustomerRepository,
  SwitchRiskSignalRepository,
} from "@warmpact/services/customers/ports";

export interface CustomersDomainModule {
  repos: {
    customers: CustomerRepository;
    switchRiskSignals: SwitchRiskSignalRepository;
  };
  useCases: {
    customers: {
      list: ExecuteListHeatCustomers;
    };
    switchRiskSignals: {
      list: ExecuteListSwitchRiskSignals;
    };
  };
}

export function buildCustomersDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CustomersDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      customers?: CustomerRepository;
      switchRiskSignals?: SwitchRiskSignalRepository;
    } = {};

    obj.customers = new CustomerRepositoryAdapter(dynamoClient);
    obj.switchRiskSignals = new SwitchRiskSignalRepositoryAdapter(dynamoClient);
    return {
      customers: obj.customers!,
      switchRiskSignals: obj.switchRiskSignals!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    customers: {
      list: new ExecuteListHeatCustomers(executionContext, idGenerator, repos.customers),
    },
    switchRiskSignals: {
      list: new ExecuteListSwitchRiskSignals(executionContext, idGenerator, repos.switchRiskSignals),
    },
  };
  return { repos, useCases: useCases as CustomersDomainModule["useCases"] };
}
