/**
 * ListReturnTemperature DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListReturnTemperatureRecordsParams } from "@warmpact/core/network";

export function createListReturnTemperatureRequest(overrides: Partial<ListReturnTemperatureRecordsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
