/**
 * GetPlainLanguageConditionReport handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: advisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getPlainLanguageConditionReport } from "@warmpact/api-server/domains/advisory/handlers";
import type { AdvisoryDDDDependencies } from "@warmpact/api-server/domains/advisory";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@warmpact/tests/shared";
import { ADVISORY_USE_CASES } from "../__factories__/use-cases.js";

describe("GetPlainLanguageConditionReport", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AdvisoryDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AdvisoryDDDDependencies>(
      ADVISORY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetPlainLanguageConditionReport, "execute").mockResolvedValue(useCaseResult);

    await getPlainLanguageConditionReport(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetPlainLanguageConditionReport.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
