/**
 * ListFaultFinding DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListFaultFindingsParams } from "@warmpact/core/diagnostics";

export function createListFaultFindingRequest(overrides: Partial<ListFaultFindingsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
