/**
 * Diagnostics DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Diagnostics Domain Module - Composition root
 *
 * DDD: Composition root for diagnostics domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  FaultFindingRepositoryAdapter,
  WorkOrderRepositoryAdapter,
} from "@warmpact/adapters/diagnostics";
import { getIdGeneratorService } from "@warmpact/adapters";
import type { AdapterDynamoDBClient } from "@warmpact/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteDispatchWorkOrder,
  ExecuteListFaultFindings,
} from "@warmpact/services/diagnostics/usecases";
// Ports (interfaces)
import type {
  FaultFindingRepository,
  WorkOrderRepository,
} from "@warmpact/services/diagnostics/ports";

export interface DiagnosticsDomainModule {
  repos: {
    faultFindings: FaultFindingRepository;
    workOrders: WorkOrderRepository;
  };
  useCases: {
    faultFindings: {
      list: ExecuteListFaultFindings;
    };
    workOrders: {
      get: ExecuteDispatchWorkOrder;
    };
  };
}

export function buildDiagnosticsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DiagnosticsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      faultFindings?: FaultFindingRepository;
      workOrders?: WorkOrderRepository;
    } = {};

    obj.faultFindings = new FaultFindingRepositoryAdapter(dynamoClient);
    obj.workOrders = new WorkOrderRepositoryAdapter(dynamoClient);
    return {
      faultFindings: obj.faultFindings!,
      workOrders: obj.workOrders!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    faultFindings: {
      list: new ExecuteListFaultFindings(executionContext, idGenerator, repos.faultFindings),
    },
    workOrders: {
      get: new ExecuteDispatchWorkOrder(executionContext, idGenerator, repos.workOrders),
    },
  };
  return { repos, useCases: useCases as DiagnosticsDomainModule["useCases"] };
}
