/**
 * DemandRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: forecasting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DemandRepository Port
 *
 * DDD: Application port for demandrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDemandForecastInput, GetDemandForecastOutput } from "../dto/demand.dto";
export interface DemandRepository {
  getDemandForecast(input: GetDemandForecastInput): Promise<GetDemandForecastOutput>;
}

export type { GetDemandForecastInput, GetDemandForecastOutput } from "../dto/demand.dto";
