/**
 * ListSwitchRiskSignal DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListSwitchRiskSignalsParams } from "@warmpact/core/customers";

export function createListSwitchRiskSignalRequest(overrides: Partial<ListSwitchRiskSignalsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
