/**
 * ExecuteListSupplyTemperatureSetpoints - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListSupplyTemperatureSetpoints Use Case
 *
 * DDD: Application use case for list Setpoint.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListSupplyTemperatureSetpointsInput, ListSupplyTemperatureSetpointsOutput } from "../dto/setpoint.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { SetpointRepository } from "../ports";

export class ExecuteListSupplyTemperatureSetpoints {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly setpoint: SetpointRepository
  ) {}

  async execute(input: ListSupplyTemperatureSetpointsInput): Promise<ListSupplyTemperatureSetpointsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.netId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.setpoint.listSupplyTemperatureSetpoints({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListSupplyTemperatureSetpointsOutput;
  }
}
