/**
 * ExecuteListReturnTemperatureRecords - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListReturnTemperatureRecords Use Case
 *
 * DDD: Application use case for list ReturnTemperature.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListReturnTemperatureRecordsInput, ListReturnTemperatureRecordsOutput } from "../dto/return-temperature.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { ReturnTemperatureRepository } from "../ports";

export class ExecuteListReturnTemperatureRecords {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly returnTemperature: ReturnTemperatureRepository
  ) {}

  async execute(input: ListReturnTemperatureRecordsInput): Promise<ListReturnTemperatureRecordsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.netId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.returnTemperature.listReturnTemperatureRecords({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListReturnTemperatureRecordsOutput;
  }
}
