/**
 * ExecuteIngestReturnTemperatureRecord - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: network
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteIngestReturnTemperatureRecord Use Case
 *
 * DDD: Application use case for get ReturnTemperature.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { IngestReturnTemperatureRecordInput, IngestReturnTemperatureRecordOutput } from "../dto/return-temperature.dto";
import type { ExecutionContextService, IdGeneratorService } from "@warmpact/services/_shared/index.js";
import type { ReturnTemperatureRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteIngestReturnTemperatureRecord {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly returnTemperature: ReturnTemperatureRepository
  ) {}

  async execute(input: IngestReturnTemperatureRecordInput): Promise<IngestReturnTemperatureRecordOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.netId();

    // All field names extracted from OpenAPI spec: annualisedCostToNetwork, connectionId, contractualMaximumC, deltaTK, exceedanceKelvin, measuredAt, returnTemperatureC, supplyTemperatureC
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).connectionId) {
      throw new ValidationError("connectionId is required");
    }
    const connectionId = (input as any).connectionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.returnTemperature.ingestReturnTemperatureRecord({ connectionId: connectionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${connectionId}`);
    }

    return entity as IngestReturnTemperatureRecordOutput;
  }
}
