/**
 * ConditionProductRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConditionProductRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConditionProductRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConditionProductRepository,
} from "@warmpact/services/guarantees";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConditionProductRepositoryDdb } from "./condition-product-repository.ddb.js";

/**
 * ConditionProductRepositoryAdapter
 *
 * Implements ConditionProductRepository port for infrastructure layer.
 */
export class ConditionProductRepositoryAdapter implements ConditionProductRepository {
  private readonly ddb: ConditionProductRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConditionProductRepositoryDdb(this.dynamoClient);
  }

  async listConditionProducts(input: Parameters<ConditionProductRepository['listConditionProducts']>[0]): Promise<Awaited<ReturnType<ConditionProductRepository['listConditionProducts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listConditionProducts(input);
  }

  async createConditionProduct(input: Parameters<ConditionProductRepository['createConditionProduct']>[0]): Promise<Awaited<ReturnType<ConditionProductRepository['createConditionProduct']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createConditionProduct(input);
  }
}
