/**
 * GuaranteeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GuaranteeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements GuaranteeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  GuaranteeRepository,
} from "@warmpact/services/guarantees";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { GuaranteeRepositoryDdb } from "./guarantee-repository.ddb.js";

/**
 * GuaranteeRepositoryAdapter
 *
 * Implements GuaranteeRepository port for infrastructure layer.
 */
export class GuaranteeRepositoryAdapter implements GuaranteeRepository {
  private readonly ddb: GuaranteeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new GuaranteeRepositoryDdb(this.dynamoClient);
  }

  async listConditionGuarantees(input: Parameters<GuaranteeRepository['listConditionGuarantees']>[0]): Promise<Awaited<ReturnType<GuaranteeRepository['listConditionGuarantees']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listConditionGuarantees(input);
  }

  async offerConditionGuarantee(input: Parameters<GuaranteeRepository['offerConditionGuarantee']>[0]): Promise<Awaited<ReturnType<GuaranteeRepository['offerConditionGuarantee']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.offerConditionGuarantee(input);
  }
}
