/**
 * OverrideAttemptRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OverrideAttemptRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements OverrideAttemptRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  OverrideAttemptRepository,
} from "@warmpact/services/guarantees";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { OverrideAttemptRepositoryDdb } from "./override-attempt-repository.ddb.js";

/**
 * OverrideAttemptRepositoryAdapter
 *
 * Implements OverrideAttemptRepository port for infrastructure layer.
 */
export class OverrideAttemptRepositoryAdapter implements OverrideAttemptRepository {
  private readonly ddb: OverrideAttemptRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new OverrideAttemptRepositoryDdb(this.dynamoClient);
  }

  async attemptSafetyFloorOverride(input: Parameters<OverrideAttemptRepository['attemptSafetyFloorOverride']>[0]): Promise<Awaited<ReturnType<OverrideAttemptRepository['attemptSafetyFloorOverride']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.attemptSafetyFloorOverride(input);
  }
}
