/**
 * SafetyFloorRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: guarantees
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SafetyFloorRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SafetyFloorRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SafetyFloorRepository,
} from "@warmpact/services/guarantees";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SafetyFloorRepositoryDdb } from "./safety-floor-repository.ddb.js";

/**
 * SafetyFloorRepositoryAdapter
 *
 * Implements SafetyFloorRepository port for infrastructure layer.
 */
export class SafetyFloorRepositoryAdapter implements SafetyFloorRepository {
  private readonly ddb: SafetyFloorRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SafetyFloorRepositoryDdb(this.dynamoClient);
  }

  async getSafetyFloors(input: Parameters<SafetyFloorRepository['getSafetyFloors']>[0]): Promise<Awaited<ReturnType<SafetyFloorRepository['getSafetyFloors']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSafetyFloors(input);
  }
}
