/**
 * Handlers for WorkOrder
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diagnostics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DiagnosticsDomainModule } from "../dependencies/diagnostics-ddd.dependencies.js";
import type { DispatchWorkOrderInput } from "@warmpact/services/diagnostics";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/diagnostics/fault-findings/{findingId}/work-order
 * Operation: dispatchWorkOrder
 */
export async function dispatchWorkOrder(
  request: FastifyRequest<{ Params: { findingId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DiagnosticsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DispatchWorkOrderInput = {
    findingId: request.params.findingId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.workOrders.get.execute(input);
  return reply.code(201).send(result);
}


