/**
 * CarbonIntensityRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CarbonIntensityRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CarbonIntensityRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CarbonIntensityRepository,
} from "@warmpact/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CarbonIntensityRepositoryDdb } from "./carbon-intensity-repository.ddb.js";

/**
 * CarbonIntensityRepositoryAdapter
 *
 * Implements CarbonIntensityRepository port for infrastructure layer.
 */
export class CarbonIntensityRepositoryAdapter implements CarbonIntensityRepository {
  private readonly ddb: CarbonIntensityRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CarbonIntensityRepositoryDdb(this.dynamoClient);
  }

  async listCarbonIntensityRecords(input: Parameters<CarbonIntensityRepository['listCarbonIntensityRecords']>[0]): Promise<Awaited<ReturnType<CarbonIntensityRepository['listCarbonIntensityRecords']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCarbonIntensityRecords(input);
  }
}
