/**
 * GetConnection DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: customers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetBuildingConnectionParams } from "@warmpact/core/customers";

export function createGetConnectionRequest(overrides: Partial<GetBuildingConnectionParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
