/**
 * RevisionTrigger DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RevisionTrigger DTOs
 *
 * DDD: Application DTOs for RevisionTrigger use cases.
 */

import type { ListRevisionTriggersParams } from "@warmpact/core/pricing/types";

export type ListRevisionTriggersInput = ListRevisionTriggersParams;

export type ListRevisionTriggersOutput = {};
